# Smmothing Or Bluring Images
* are used to remove the noise from the images and it use diverse linear filter because linear filter easy to achieve and relatively fast

# Types Of Smoothing 
1. Blur (Averaging)
2. Gaussian Filter 
3. Median Filter 
4. Bilateral Filter 

* **Averaging Matrix ==> K = 1 /(Number Of Hight / # Of Width)**
* K = 1/9*[1 1 1]
             [1 1 1]
             [1 1 1]]

# Note 
* When increase filter size this increase the possbility of the image becoming blur 
* Example When increase average from (5,5) To --> (11,11) ==> Image become Blur Image


In [1]:
import cv2 as cv
import matplotlib.pyplot as plt 
import numpy as np 
import os 
os.chdir(R"C:\\Users\\Alhou\\3. OpenCV\\0- OpenCV\\Data\\Images")
#Convert Early Image For BGR To GrayScale
img = cv.imread('early_18000.jpg')
average = cv.blur(img,(5,5)) # Mean of pixels
img = cv.resize(img,(500,300))
avg =cv.resize(average,(500,300))
#Images 
cv.imshow('Original Image',img)
cv.imshow('Averaging Image',avg)
cv.waitKey(0)
cv.destroyAllWindows()

* Applying Gaussian Filter 

* k = 1/273 * 
          [1 4 7 4 1]
          [4 16 26 16 4]
          [7 26 '41' 26 7]
          [4 16 26 16 4]
          [1 4 7 4 1]
          

In [4]:
#Read Same Image 
gblur = cv.GaussianBlur(img,(5,5),0)
#Show Images 
gblur = cv.resize((gblur),(500,300))
cv.imshow('Original Image',img)
cv.imshow('Average Image',avg)
cv.imshow('Gaussian Image',gblur)
cv.waitKey(0)
cv.destroyAllWindows()

# Median Smoothing 
* Median Using in --> Salt and paper imaage

In [3]:
img1 = cv.imread('lena.jpg')
bilteral = cv.bilateralFilter(img1,9,75,75)
median = cv.medianBlur(img1,5)
cv.imshow('Orignal Image',img1)
cv.imshow('Bilteral Filter' , bilteral)
cv.imshow('Median Image',median)
cv.waitKey(0)
cv.destroyAllWindows()