In [1]:
import cv2 as cv 
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd
import os 
os.chdir(R"D:\\AI\\AI Models\\3. OpenCV\\0- OpenCV\\Data\\Images") 
img = cv.imread('cv.png')
img =cv.resize(img,(512,512))
imggray = cv.cvtColor(img,cv.COLOR_BGR2GRAY)
_,thresh = cv.threshold(imggray,20,255,0)
contours ,hierarchy = cv.findContours(thresh,cv.RETR_TREE,cv.CHAIN_APPROX_NONE)
print('The number of contours are --> ', str(len(contours)))
print(contours[0])
cv.drawContours(img,contours,-1,(0,255,0),3)
cv.imshow('Image',img)
cv.imshow('Gray Image',imggray)
cv.imshow('Thresh',thresh)
cv.waitKey(0)
cv.destroyAllWindows()

The number of contours are -->  3
[[[329 204]]

 [[328 205]]

 [[327 205]]

 ...

 [[332 206]]

 [[331 205]]

 [[330 204]]]
