In [1]:
import cv2 as cv 
import numpy as np 
import os 
os.chdir(R"D:\\AI\\AI Models\\3. OpenCV\\0- OpenCV\\Data\\Images")
img = cv.imread('shappes.jpg')
#Convert Photo from BGR To Gray 
imgGrey = cv.cvtColor(img,cv.COLOR_BGR2GRAY)
#Apply Threshold because convert phot fom Grayscale to (black and white)
_,thresh = cv.threshold(imgGrey,240,255,cv.THRESH_BINARY)
#Applying Contours 
contours,_ = cv.findContours(thresh,cv.RETR_TREE,cv.CHAIN_APPROX_NONE)
cv.imshow('Orignal Image',img)
for contour in contours:
    #get appromation for all contours and it's length also and multiply it with small value to modify 
    approx = cv.approxPolyDP(contour,0.01 * cv.arcLength(contour,True),True)
    cv.drawContours(img,[approx],0,(0,0,0),5)
    x = approx.ravel()[0]
    y = approx.ravel()[1]-7
    if len(approx) == 3 :
        print (approx)
        cv.putText(img,"Triangle",(x,y),cv.FONT_HERSHEY_COMPLEX,0.5,(0,0,0))
    elif len (approx) ==4:
        x1,y1,w,h = cv.boundingRect(approx)
        aspectRatio = float(w)/h
        if aspectRatio>= 0.95 and aspectRatio <=1.05:
            cv.putText(img,'Sqaue',(x,y),cv.FONT_HERSHEY_COMPLEX,0.5,(0,0,0))
        else : cv.putText(img,'Rectangle',(x,y),cv.FONT_HERSHEY_COMPLEX,0.5,(0,0,0))
    elif len(approx)==5:cv.putText(img,'Pentagon',(x,y),cv.FONT_HERSHEY_COMPLEX,0.5,(0,0,0))
    elif len(approx) ==10:cv.putText(img,"Star",(x,y),cv.FONT_HERSHEY_COMPLEX,0.5,(0,0,0))
    else:cv.putText(img,"Circle",(x,y),cv.FONT_HERSHEY_COMPLEX,0.5,(0,0,0))
cv.imshow('After_Apply_Contours',img)
cv.waitKey(0)
cv.destroyAllWindows()

[[[258 252]]

 [[309 341]]

 [[207 340]]]
